CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_EXT_POWER=y

CONFIG_PMW3610_ALT=y
# CONFIG_PMW3610_ALT_LOG_LEVEL_DBG=y
# CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=12

# Uncomment if sensor reports wrong product ID on boot (power-up timing issue)
# CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=1000

# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
